name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cbd:latest .

    # Push Docker Image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cbd:latest

    # Deploy Docker Container on EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Pull the latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/cbd:latest
          
          # Stop and remove any existing container
          docker stop cbd || true
          docker rm cbd || true
          
          # Run the new container
          docker run -d -p 5000:5000 --name cbd ${{ secrets.DOCKER_USERNAME }}/cbd:latest
